import { back, chooseDate, choosePlace, expect, expectSchedule, readSavedSetting, test } from './fixtures'

test('хиджра, поправка и нативные списки сохраняют гражданский день и расписание', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('./')
  await choosePlace(page)
  const times = await page.locator('.event-row time').allTextContents()
  await page.getByRole('button', { name: 'Выбрать дату' }).click()
  await expect(page.getByRole('button', { name: 'Назад' })).toBeFocused()
  await expect(page.getByRole('button', { name: 'Сегодня' })).toHaveCount(0)
  await expect(page.getByRole('combobox')).toHaveCount(4)
  await page.getByRole('combobox', { name: 'Календарь' }).selectOption('hijri')
  await expect(page.getByRole('combobox')).toHaveCount(5)
  await expect(page.getByRole('combobox', { name: 'Год' })).toHaveValue('1448')
  await expect(page.getByRole('combobox', { name: 'День' })).toHaveValue('22')
  await expect(page.getByRole('combobox', { name: 'Месяц' }).locator('option:checked')).toHaveText('раби аль-авваль')
  await expect(page.getByText(/Умм|Метод/)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Готово' })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Поправка даты' }).selectOption('1')
  await expect(page.getByRole('combobox', { name: 'День' })).toHaveValue('23')
  await expect(page.getByRole('button', { name: 'Сегодня' })).toHaveCount(0)
  for (const field of await page.getByRole('combobox').all()) {
    const rect = await field.boundingBox()
    expect(rect?.width).toBeGreaterThanOrEqual(44)
    expect(rect?.height).toBeGreaterThanOrEqual(44)
    await expect(field).toHaveCSS('font-size', '16px')
  }
  expect(await page.locator('.screen-content').evaluate(node => node.scrollWidth - node.clientWidth)).toBeLessThanOrEqual(1)
  await back(page)
  await expect(page.locator('#home-date')).toBeFocused()
  await expect(page.locator('#home-date')).toHaveText('23 раби I')
  await expect(page.locator('#home-date')).toHaveAccessibleDescription('23 раби I')
  await expectSchedule(page)
  expect(await page.locator('.event-row time').allTextContents()).toEqual(times)
  await page.getByRole('button', { name: 'Выбрать дату' }).click()
  await page.getByRole('combobox', { name: 'День' }).selectOption('24')
  await expect(page.getByRole('button', { name: 'Сегодня' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Календарь' }).selectOption('gregorian')
  await expect(page.getByRole('combobox', { name: 'День' })).toHaveValue('5')
  await expect(page.getByRole('combobox', { name: 'Поправка даты' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Сегодня' }).click()
  await expect(page.getByRole('combobox', { name: 'День' })).toBeFocused()
  await expect(page.getByRole('button', { name: 'Сегодня' })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Календарь' }).selectOption('hijri')
  await expect(page.getByRole('combobox', { name: 'Поправка даты' })).toHaveValue('1')
  await expect.poll(() => readSavedSetting(page, 'calendarPreferences')).toEqual({ calendar: 'hijri', correction: 1 })
  await page.reload()
  await expect(page.locator('#home-date')).toHaveText('23 раби I')
  await expectSchedule(page)
  expect(await page.locator('.event-row time').allTextContents()).toEqual(times)
  await page.getByRole('button', { name: 'Настройки' }).click()
  await expect(page.getByText('Календарь')).toHaveCount(0)
  await page.getByRole('button', { name: 'О приложении' }).click()
  await expect(page.getByText('Дата хиджры рассчитывается по календарю Умм аль-Кура.')).toBeVisible()
  expect(errors).toEqual([])
})

test('списки ограничивают день длиной месяца и сохраняют клавиатурный фокус', async ({ page }) => {
  await page.goto('./')
  await choosePlace(page)
  await chooseDate(page, '2024-01-31')
  await page.getByRole('button', { name: 'Выбрать дату' }).click()
  await expect(page.getByRole('button', { name: 'Назад' })).toBeFocused()
  const month = page.getByRole('combobox', { name: 'Месяц' })
  await month.focus()
  await month.selectOption('2')
  await expect(month).toBeFocused()
  await expect(page.getByRole('combobox', { name: 'День' })).toHaveValue('29')
  await page.getByRole('combobox', { name: 'Год' }).selectOption('2025')
  await expect(page.getByRole('combobox', { name: 'День' })).toHaveValue('28')
  await page.goBack()
  await expect(page.locator('#home-date')).toBeFocused()
  await expect(page.locator('#home-date time')).toHaveAttribute('datetime', '2025-02-28')
})

test('экран даты доступен при двойном размере текста на узком экране', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 640 })
  await page.goto('./')
  await choosePlace(page)
  await page.getByRole('button', { name: 'Выбрать дату' }).click()
  await page.getByRole('combobox', { name: 'Календарь' }).selectOption('hijri')
  await page.evaluate(() => document.documentElement.style.fontSize = '32px')
  const correction = page.getByRole('combobox', { name: 'Поправка даты' })
  await correction.scrollIntoViewIfNeeded()
  await expect(correction).toBeInViewport()
  await correction.selectOption('1')
  await expect(correction).toHaveValue('1')
  expect(await page.locator('.screen-content').evaluate(node => node.scrollWidth - node.clientWidth)).toBeLessThanOrEqual(1)
  await back(page)
  await expect(page.locator('#home-date')).toBeInViewport()
})
