import type { Locator, Page } from '@playwright/test'
import { back, choosePlace, expectSchedule, openSource, setSource, expect, test } from './fixtures'

async function geometry(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  const panel = page.locator('.app-screen')
  await expect(panel).toHaveCSS('padding', '16px')
  await expect(panel).toHaveCSS('border-radius', '38px')
  await expect(panel).toHaveCSS('background-color', 'rgb(40, 40, 40)')
  const bounds = await panel.boundingBox()
  const viewport = page.viewportSize()
  if (!bounds || !viewport) throw new Error('Нет размеров экрана')
  expect(bounds.y).toBeGreaterThanOrEqual(0)
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(viewport.height + 1)
  for (const part of ['.screen-top', '.screen-bottom']) {
    const node = page.locator(part)
    if (!await node.count()) continue
    const rect = await node.boundingBox()
    if (!rect) throw new Error('Нет размеров кнопок')
    expect(rect.x - bounds.x).toBeCloseTo(16, 0)
    expect(bounds.x + bounds.width - rect.x - rect.width).toBeCloseTo(16, 0)
    if (part === '.screen-top') expect(rect.y - bounds.y).toBeCloseTo(16, 0)
    else expect(bounds.y + bounds.height - rect.y - rect.height).toBeCloseTo(16, 0)
  }
  for (const button of await panel.locator('button, input, select, summary').all()) {
    const rect = await button.boundingBox()
    if (rect) {
      expect(rect.width).toBeGreaterThanOrEqual(44)
      expect(rect.height).toBeGreaterThanOrEqual(44)
    }
  }
}

async function aligned(left: Locator, right: Locator) {
  const a = await left.boundingBox(), b = await right.boundingBox()
  if (!a || !b) throw new Error('Нет размеров элементов')
  expect(a.x).toBeCloseTo(b.x, 0)
}

for (const viewport of [{ width: 320, height: 640 }, { width: 390, height: 844 }, { width: 844, height: 390 }, { width: 1280, height: 900 }]) {
  test(`${viewport.width}×${viewport.height}: экраны, поля 16, единая типографика и доступные действия`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.setViewportSize(viewport)
    await page.goto('./')
    await choosePlace(page)
    await expect(page).toHaveTitle(/Salah/)
    await expect(page.locator('.event-row[aria-current=true]')).toContainText('Зухр')
    await geometry(page)
    await expect(page.getByRole('heading', { name: 'Salah' })).toHaveCount(0)
    await page.screenshot({ path: `/tmp/salah-final-home-${viewport.width}.png` })
    await expectSchedule(page)
    await geometry(page)
    for (const row of await page.locator('.event-row').all()) await expect(row).toHaveCSS('font-size', '20px')
    await expect(page.locator('.event-row[aria-current=true]')).toContainText('Зухр')
    const fajr = page.getByText('Фаджр в мечети', { exact: true })
    expect(await fajr.evaluate(node => node.getClientRects().length)).toBe(1)
    await page.screenshot({ path: `/tmp/salah-final-schedule-${viewport.width}.png` })
    await page.locator('#home-location').click()
    await geometry(page)
    await aligned(page.getByRole('button', { name: 'Назад' }), page.getByRole('button', { name: 'Найти город' }))
    await page.getByRole('button', { name: 'Найти город' }).click()
    await page.getByRole('searchbox').fill('Стамбул')
    const result = page.getByRole('button', { name: 'Стамбул, Стамбул, Турция', exact: true })
    await expect(result).toBeVisible()
    await geometry(page)
    await aligned(page.getByRole('button', { name: 'Отмена' }), page.getByRole('searchbox'))
    await aligned(page.getByRole('searchbox'), result)
    await expect(result).toHaveCSS('border-radius', '16px')
    await page.screenshot({ path: `/tmp/salah-final-search-${viewport.width}.png` })
    await page.getByRole('button', { name: 'Отмена' }).click()
    await expect(page.getByRole('button', { name: 'Найти город' })).toBeFocused()
    await back(page)
    await openSource(page)
    await geometry(page)
    await setSource(page, 'Ручной расчёт')
    await page.getByRole('button', { name: 'Параметры' }).click()
    await geometry(page)
    await back(page)
    await back(page)
    await page.getByRole('button', { name: 'Поделиться' }).click()
    await geometry(page)
    await expect(page.getByRole('textbox')).toHaveCSS('text-align', 'center')
    const qr = await page.getByRole('img', { name: /QR-код/ }).boundingBox()
    const link = await page.getByRole('textbox').boundingBox()
    if (!qr || !link) throw new Error('Нет QR или ссылки')
    expect(qr.y + qr.height).toBeLessThan(link.y)
    await page.screenshot({ path: `/tmp/salah-final-share-${viewport.width}.png` })
    expect(errors).toEqual([])
  })
}

test('поиск использует видимую высоту при клавиатуре и восстанавливается после закрытия', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./')
  await choosePlace(page)
  await page.locator('#home-location').click()
  await page.getByRole('button', { name: 'Найти город' }).click()
  await page.getByRole('searchbox').fill('Москва')
  await expect(page.getByRole('button', { name: 'Москва, Москва, Россия' })).toBeVisible()
  await page.evaluate(() => {
    const viewport = window.visualViewport
    if (!viewport) throw new Error('Нет visualViewport')
    Object.defineProperties(viewport, { height: { configurable: true, value: 360 }, offsetTop: { configurable: true, value: 40 } })
    viewport.dispatchEvent(new Event('resize'))
  })
  await expect(page.locator('.app-layout')).toHaveCSS('height', '360px')
  await expect(page.locator('.app-layout')).toHaveCSS('top', '40px')
  const result = await page.getByRole('button', { name: 'Москва, Москва, Россия' }).boundingBox()
  if (!result) throw new Error('Результат скрыт')
  expect(result.y + result.height).toBeLessThanOrEqual(400)
  await page.screenshot({ path: '/tmp/salah-final-keyboard.png' })
  await page.evaluate(() => {
    const viewport = window.visualViewport
    if (!viewport) throw new Error('Нет visualViewport')
    Reflect.deleteProperty(viewport, 'height'); Reflect.deleteProperty(viewport, 'offsetTop')
    viewport.dispatchEvent(new Event('resize'))
  })
  await expect(page.locator('.app-layout')).toHaveCSS('height', '844px')
})

test('календарь обновляет главную без перехода, Сегодня возвращает живое расписание', async ({ page, context }) => {
  await page.goto('./')
  await choosePlace(page)
  const historyLength = await page.evaluate(() => history.length)
  await page.getByLabel('Выбрать дату').focus()
  await page.getByLabel('Выбрать дату').fill('2026-09-01')
  await expect(page.getByRole('region', { name: 'Главная', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Назад', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Расписание', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Выбрать дату')).toBeFocused()
  expect(await page.evaluate(() => history.length)).toBe(historyLength)
  expect(context.pages()).toHaveLength(1)
  await expect(page.getByRole('listitem')).toHaveCount(8)
  await expect(page.getByRole('timer')).toHaveCount(0)
  await expect(page.locator('[aria-current=true]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Сегодня' }).click()
  await expect(page.getByRole('timer')).toBeVisible()
  await expect(page.getByLabel('Выбрать дату')).toHaveValue('2026-09-04')
})

test('клавиатура и браузерный возврат восстанавливают фокус без скрытых экранов', async ({ page }) => {
  await page.goto('./')
  await choosePlace(page)
  await page.locator('#home-location').focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Назад' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Найти город' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('searchbox')).toBeFocused()
  await page.goBack()
  await expect(page.getByRole('button', { name: 'Найти город' })).toBeFocused()
  await page.goBack()
  await expect(page.locator('#home-location')).toBeFocused()
  await expect(page.locator('.app-screen')).toHaveCount(1)
})

test('поделиться копирует каноническую ссылку; отказ буфера оставляет выделенный адрес', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('./')
  await page.getByRole('button', { name: 'Настройки' }).click()
  await page.getByRole('button', { name: 'Поделиться' }).click()
  await page.getByRole('button', { name: 'Скопировать ссылку' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('https://halsab.github.io/salah-pwa/')
  await expect(page.getByRole('button', { name: 'Скопировано' })).toBeVisible()
  await back(page)
  await expect(page.getByRole('button', { name: 'Поделиться' })).toBeFocused()
  await page.getByRole('button', { name: 'Поделиться' }).click()
  await page.evaluate(() => { navigator.clipboard.writeText = () => Promise.reject(new Error('denied')) })
  await page.getByRole('button', { name: 'Скопировать ссылку' }).click()
  await expect(page.getByRole('textbox')).toBeFocused()
  expect(await page.getByRole('textbox').evaluate((node: HTMLTextAreaElement) => node.selectionEnd - node.selectionStart)).toBe('https://halsab.github.io/salah-pwa/'.length)
  await expect(page.getByRole('status')).toContainText('Скопируйте')
})

test('тема остаётся монохромной; недавних не больше трёх, текущий город исключён', async ({ page }) => {
  await page.goto('./')
  await choosePlace(page)
  for (const name of ['Набережные Челны', 'Апастово', 'Арск', 'Балтаси']) await choosePlace(page, name, new RegExp(`${name}.*ДУМ РТ`))
  await page.locator('#home-location').click()
  const recent = page.getByRole('region', { name: 'Недавние города' })
  await expect(recent.getByRole('button')).toHaveCount(3)
  await expect(recent.getByRole('button', { name: 'Балтаси' })).toHaveCount(0)
  await page.reload()
  await page.locator('#home-location').click()
  await expect(recent.getByRole('button')).toHaveCount(3)
  for (const colorScheme of ['light', 'dark'] as const) {
    await page.emulateMedia({ colorScheme, reducedMotion: 'reduce' })
    await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(0, 0, 0)')
    await expect(page.locator('.app-screen')).toHaveCSS('background-color', 'rgb(40, 40, 40)')
  }
})


test('увеличение текста вдвое сохраняет читаемый список и доступ к действиям', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./')
  await choosePlace(page)
  await page.evaluate(() => { document.documentElement.style.fontSize = '32px' })
  await expectSchedule(page)
  await expect(page.locator('.event-row').first()).toHaveCSS('font-size', '40px')
  expect(await page.locator('.screen-content').evaluate(node => node.scrollWidth - node.clientWidth)).toBeLessThanOrEqual(1)
  await page.getByText('Иша', { exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByText('Иша', { exact: true })).toBeInViewport()
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await page.getByRole('button', { name: 'Данные и конфиденциальность' }).click()
  await expect(page.getByRole('button', { name: 'Удалить данные' })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  await page.screenshot({ path: '/tmp/salah-final-text-200.png' })
})
